env:
  BUILD_START: $BUILD_START
steps:
  - group: ":golang: :test_tube: :opentelemetry: Test - with Buildevents"
    steps:
      - command:
          - STEP_START=$$(date +%s) STEP_SPAN_ID="$${BUILDKITE_JOB_ID}" /.buildkite/scripts/go_test.sh
        key: "test-buildevents"
        parallelism: 5
        soft_fail: true
  - group: ":golang: :test_tube: :opentelemetry: Test - with Buildkite Markers"
    steps:
      - command: /.buildkite/scripts/no_build_events_go_test.sh
        plugins:
          - tendnz/honeymarker#v1.0.5:
              message: "${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_BUILD_NUMBER}"
              writekey: "$$BUILDEVENT_APIKEY"
              dataset: "buildkite-markers"
              url: "${BUILDKITE_BUILD_URL}"
        key: "test-buildkite-markers"
        parallelism: 5
        soft_fail: true
        depends_on:
          - test-buildevents
  - wait: ~
    depends_on:
      - test-buildkite-markers
      - test-buildevents
  - command: STEP_START=$$(date +%s) STEP_SPAN_ID="$${BUILDKITE_JOB_ID}" .buildkite/scripts/annotate_build.sh
    label: ":broom: :opentelemetry: Cleanup and Finish Build in Honeycomb"
